# 1/ Project name -------------------------------------------------
# Must be lower-case, no spaces and no invalid path chars.
# Will be used also as the WP database name
COMPOSE_PROJECT_NAME: wordpress

# 2/ Database user and password -----------------------------------------
# Set non-root database user if wanted (optional)
DATABASE_PASSWORD: "{{ vault_database_password }}"
DATABASE_USER: wordpress

# 3/ For wordpress auto-install and auto-configuration -------------------
WORDPRESS_WEBSITE_TITLE: "Blog"

# URL
WORDPRESS_URL: "wordpress.cloud-1.nimon.fr"
PHPMYADMIN_URL: "pma.cloud-1.nimon.fr"
WORDPRESS_WEBSITE_URL: "http://{{ WORDPRESS_URL }}"
# WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: localhost
WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/blog/%postname%/"

# Website admin identification. Specify a strong password
WORDPRESS_ADMIN_USER: "wordpress"
WORDPRESS_ADMIN_PASSWORD: "{{ vault_wordpress_admin_password }}"
WORDPRESS_ADMIN_EMAIL: "your-email@example.com"

# 4/ Software versions -----------------------------------------------
WORDPRESS_VERSION: latest
MYSQL_VERSION: latest
PHPMYADMIN_VERSION: latest

# 5/ Ports: Can be changed -------------------------------------------
# WEBSITES_PORT: 80
# WEBSITES_SECURE_PORT: 443

# 6/ Volumes on host --------------------------------------------------
WORDPRESS_VOLUME: wordpress
DATABASE_VOLUME: db

# 7/ Healthcheck availability of host services (mysql and woordpress server)
# Waiting time in second
WAIT_BEFORE_HOSTS: 5
WAIT_AFTER_HOSTS: 5
WAIT_HOSTS_TIMEOUT: 300
WAIT_SLEEP_INTERVAL: 60
WAIT_HOST_CONNECT_TIMEOUT: 5

# 8/ Used only in online deployement --------------------------------------
#WORDPRESS_WEBSITE_URL_WITHOUT_WWW: example.com
#PHPMYADMIN_WEBSITE_URL_WITHOUT_HTTP: sql.example.com
