---
- name: Commons
  tags: commons
  gather_facts: true
  hosts: all
  roles:
    - role: common

- name: Setup Website
  tags: website
  gather_facts: true
  vars_files:
    - group_vars/docker.yml
    - group_vars/vault
  hosts: all
  roles:
    - role: website

- name: Auto-setup WordPress
  tags: wordpress
  gather_facts: true
  vars_files:
    - group_vars/docker.yml
    - group_vars/vault
  hosts: all
  roles:
    - role: wp_auto-config
