- name: "Pull phpmyadmin image"
  tags: phpmyadmin
  docker_image:
    name: phpmyadmin
    source: pull
  register: phpmyadmin_image

- name: "Create phpmyadmin container"
  tags: phpmyadmin
  docker_container:
    name: phpmyadmin
    image: phpmyadmin
    state: started
    restart_policy: always
    env:
      PMA_HOST: "mysql"
      PMA_USER: "{{ mysql_user }}"
      PMA_PASSWORD: "{{ mysql_password }}"
      PMA_DATABASE: "{{ mysql_database }}"
    volumes:
      - phpmyadmin:/var/www/html
    ports:
      - "8080:80"
    networks:
      - name: mysql
  register: phpmyadmin_container
