# - name: Copy docker-compose.yml
#   tags: website
#   copy:
#     src: docker-compose.yml
#     dest: /home/{{ ansible_user }}/docker-compose.yml
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0644
#   register: docker_compose_yml

- name: Copy docker-compose
  tags: website
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Run docker-compose
  tags: website
  become: true
  shell: |
    docker compose --project-directory /home/{{ ansible_user }}/ \
      -f /home/{{ ansible_user }}/docker-compose.yml up -d
  register: docker_compose
