# - name: Copy docker-compose.yml
#   tags: website
#   copy:
#     src: docker-compose.yml
#     dest: {{ ansible_env['HOME'] }}/docker-compose.yml
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0644

- name: Copy docker-compose
  tags: website
  template:
    src: docker-compose.yml.j2
    dest: "{{ ansible_env['HOME'] }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Run docker compose pull
  tags: website
  become: true
  shell: |
    docker compose --project-directory {{ ansible_env['HOME'] }} \
      -f {{ ansible_env['HOME'] }}/docker-compose.yml pull

- name: Run docker-compose
  tags: website
  become: true
  shell: |
    docker compose --project-directory {{ ansible_env['HOME'] }} \
      -f {{ ansible_env['HOME'] }}/docker-compose.yml up -d
