---
- name: Upgrade all packages to the latest version
  tags: packages
  become: true
  apt:
    update_cache: yes
    upgrade: dist
    state: latest

- name: Install required packages
  tags: packages
  become: true
  apt:
    update_cache: yes
    pkg:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - git
    state: latest

- name: Install Docker
  tags: docker_install
  import_tasks: docker.yml
