- name: Copy wcli files
  tags: ["website", "wordpress"]
  copy:
    src: wpcli
    dest: "{{ ansible_env['HOME'] }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy wcli template
  tags: ["website", "wordpress"]
  template:
    src: wp-auto-config.yml.j2
    dest: "{{ ansible_env['HOME'] }}/wp-auto-config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Setup WordPress
  tags: ["website", "wordpress"]
  become: true
  shell: |
    docker compose --project-directory {{ ansible_env['HOME'] }}/ \
      -f docker-compose.yml -f wp-auto-config.yml run --rm wp-auto-config
